### PR TITLE
fix(lean): update slot in main loop of `ValidatorService` at `t=0`

### LINKED ISSUE #716: Lean 3SF fails to justify and finalize after some number of slots
### Describe the bug

@syjn99's machine [stops justifying/finalizing around slot 100](https://github.com/ReamLabs/ream/pull/709#pullrequestreview-3126194959) while mine stops around 86, followed by exponential increase in `compute_block_root` time.

Since `compute_state_root` increases a lot less aggressively I think it might be to do with `block.votes` not being updated correctly.

Image

Image

### Steps to reproduce

1. Run metrics services with `cd metrics/ && docker compose up`
2. Run lean node with `cargo run --release lean_node --network ephemery --metrics`
3. Check the timing in grafana: http://localhost:3000

### Platform(s)

_No response_

### What version/commit are you on?

https://github.com/ReamLabs/ream/pull/709/commits/cfe3f044405d0e0552bbcd211cc8cc28694f6ece

### If you've built Ream from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by syjn99**
### What was wrong?

 

Fixes #716.

After spinning up few devnets in my local machine, I found that current logic for calculating the `current_slot` is fragile **especially when the interval tick is fired few ms earlier**.

```log
2025-08-18T11:23:34.006068Z  INFO ream_validator_lean::service: Validator 1 proposing block for slot 153 (tick 604)
2025-08-18T11:23:34.006418Z  INFO ream_validator_lean::service: Validator 1 built block: slot=153, parent=0x2f6166c042bafa95928ee93563d991d00f7fa182428a2b18e8c7e7efd94f8371, votes=0, state_root=0x2c7095bfedae7d21bae1daf49ad940e9b3ded04ff189202fd12e9525a092d34d
// Skipping...
2025-08-18T11:23:36.001312Z  INFO ream_chain_lean::service: Computing safe target at slot 153 (tick 606)
2025-08-18T11:23:36.999610Z  INFO ream_chain_lean::service: Accepting new votes at slot 153 (tick 607)
===
2025-08-18T11:23:37.998016Z  INFO ream_validator_lean::service: Validator 1 proposing block for slot 153 (tick 608)
2025-08-18T11:23:37.998453Z  INFO ream_validator_lean::service: Validator 1 built block: slot=153, parent=0xf2feb7654aa29f3b42e028d360063edc60c3339c3ec1d0e15c7b175503cf2e3a, votes=4, state_root=0xfb530c7115421cf7e2f7ce55f79de752dc7cce87fe622f0f8bc37a6f4a89ac73
```

As you can see, for tick `604` and `608` the node proposes a block for slot number `153`.  As `Block.slot` is crucial for consensus (e.g., see `is_justifiable_slot`, it uses `target_block.slot`.), one missing piece would affect the chain afterwards.

There are several reasons that the consensus is broken:
1. Block proposer decides the slot number **immediately** when a slot starts. As I described, this is quite fragile.
2. At this moment, we only run a network with a single node, which means if something bad happens, it will never get recovered (and this is why we need more nodes for network stability :)).

### How was it fixed?

 

Update `slot` at `t=0`, and pass it as an argument for `propose_block`. Share [similar logic](https://github.com/ReamLabs/ream/blob/master/crates/common/validator/beacon/src/validator.rs#L137-L157) with existing beacon validator client.

### Testing

Thanks to #709, I tested multiple times, and it is stable over 500+ slot. I forgot to take a screenshot, but here's a part of the log:

```log
2025-08-18T13:33:41.013764Z  INFO ream_validator_lean::service: Validator 2 proposing block for slot 622 (tick 2480)
2025-08-18T13:33:41.014146Z  INFO ream_validator_lean::service: Validator 2 built block: slot=622, parent=0xf81d302aa54e550d5bc00f209438885083b68bdb8fcc36ac7f3a16d3372ed6e4, votes=4, state_root=0x908dc8794f1d25ffa18f9785f536abdca7dc653257e58f20172f93cc9d9652d2
2025-08-18T13:33:42.013032Z  INFO ream_validator_lean::service: Starting vote phase at slot 622 (tick 2481): 4 validator(s) voting
2025-08-18T13:33:42.013579Z  INFO ream_validator_lean::service: Built vote template for head Checkpoint { root: 0xf81d302aa54e550d5bc00f209438885083b68bdb8fcc36ac7f3a16d3372ed6e4, slot: 621 } at slot 622 with target 620
2025-08-18T13:33:42.013820Z  INFO ream_chain_lean::service: Received unsigned vote from validator 0 for head Checkpoint { root: 0xf81d302aa54e550d5bc00f209438885083b68bdb8fcc36ac7f3a16d3372ed6e4, slot: 621 } / source_slot 617 at slot 622
```

### To-Do

 
- [x] I have read [CONTRIBUTING.md](https://github.com/ReamLabs/ream/blob/master/CONTRIBUTING.md).
- [x] This PR title follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### CODE REVIEW

File: crates/common/validator/lean/src/service.rs [hunk 1]
```diff
@@ -72,10 +74,11 @@ impl ValidatorService {
                 _ = interval.tick() => {
                     match tick_count % 4 {
                         0 => {
+                            slot += 1;
```
Comment (unnawut) [inline crates/common/validator/lean/src/service.rs:77]: At first glance I thought this will prevent starting nodes after `genesis_time` but this is already the case with [`create_lean_clock_interval()`](https://github.com/ReamLabs/ream/blob/master/crates/common/chain/lean/src/clock.rs#L8-L32) so looks okay to me.

We just need to update this logic when we have sync feature.
