### PR TITLE
fix: align with latest chaining & 3SF-mini leanspecs

### LINKED ISSUE #753: Align lean consensus code with latest STF specs
### Describe the feature

The PR (https://github.com/leanEthereum/leanSpec/pull/15) is not merged yet but the changes are small enough.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by unnawut**
### What was wrong?

Aligning with the latest leanspecs on chaining & consensus: https://github.com/leanEthereum/leanSpec/pull/15

Closes #753

### How was it fixed?

- Genesis block is now slot 0 instead of slot 1
  - [Genesis state prefilling](https://github.com/ReamLabs/ream/pull/755/files#diff-f03aa18a3943df16ea508547d39e09a9b52b886163d3ab3ab93bb953bf08c29fL32-L40) is removed as it's already handled by `LeanState::process_block_header`
- Validators now start proposing & attesting from slot 1 instead of slot 2
  - So `SLOT_OFFSET` is now 1 instead of 2
- `LeanChain::build_vote` takes a `slot: u64` input instead of relying on `get_current_slot()` that might have time drift
- Expanded 3SF-mini's `ream_consensus_lean::process_block()` into leanSpec's:
  - `LeanState::state_transition()`
  - `LeanState::process_slots()`
  - `LeanState::process_slot()`
  - `LeanState::process_block()`
  - `LeanState::process_block_header()`
  - `LeanState::process_operations()`
  - `LeanState::process_attestations()`
- Added [`Attestation`](https://github.com/leanEthereum/leanSpec/pull/15/files#diff-2125e997632f26307bfecdca904ab86653f70f04d2e3a1041f5d3ad97b422609R119-R129) container
- Update `SignedVote` and `Vote` containers to align with the [specs](https://github.com/leanEthereum/leanSpec/blob/main/docs/client/containers.md#signedvote)
- Multiple votes are now called attestations. Single votes are still called `Vote` and `SignedVote`.
- Using `SignedBlock` instead of `Block` in `propose_block()` because `state_transition()` takes in `SignedBlock`
- Instead of looping `process_block()` when adding valid votes to a new block, switching to `process_attestations()` instead because `process_block()` now mimics beacon state transition and does a lot more than just processing votes, unlike 3sf-mini.py that's [mainly processing votes](https://github.com/ethereum/research/blob/master/3sf-mini/consensus.py#L73-L110).
  - Because of `process_attestations()` mutates the block, `state.latest_block_header.body_root` needs to be [recalculated after attestations are processed](https://github.com/ReamLabs/ream/pull/755/files#diff-96d6d875c704fdb8e3c370e1d7afb8e1ee74eb3a32c3d42fb25eb32f44ac5e58R163-R166).
- Replace the empty struct `PQSignature` with `FixedBytes<4000>` to follow https://github.com/leanEthereum/leanSpec/pull/16
- Fixed dependency processing where we're [adding new signatures](https://github.com/ReamLabs/ream/pull/755/files#diff-61106eb07bb601a66d9284a7fd245ea1ed439585c971910f64cea8558f9f35d6L198-L213) instead of using the actual signed containers
- Wrapped `SignedVote` and `SignedBlock` in `Arc` to fix `large size difference between variants` error
- Added more logging in general for consensus debugging

### To-Do

 
- [x] I have read [CONTRIBUTING.md](https://github.com/ReamLabs/ream/blob/master/CONTRIBUTING.md).
- [x] This PR title follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### CODE REVIEW

**Comment by unnawut** [comment]
Just a quick devlog that I initially tried to apply https://github.com/leanEthereum/leanSpec/pull/15 completely into ream codebase, but the PR itself is not the complete picture yet as the fork choice, block proposal etc. also needs to change from 3SF-mini.

So instead of throwing the entirety of specs PR into ream and breaking the working consensus, I'm now going to mirror as much structure as possible from the specs but commenting out parts so that we can merge the PR and still run ream local devnet with finalization.

**Comment by unnawut** [comment]
Forgot to update that I managed to apply all but 1 condition left now so aiming to fix that by today.

But agree we don't need to merge this until the specs PR is merged

**Comment by unnawut** [comment]
Works now but will convert to ready for review once https://github.com/leanEthereum/leanSpec/pull/15 is merged

Screenshot 2025-09-04 at 18 24 13

Screenshot 2025-09-04 at 20 03 49

**Comment by unnawut** [comment]
Remaining: Update votes to attestations when relevant

File: crates/common/consensus/lean/src/block.rs [hunk 1]
```diff
@@ -15,7 +14,7 @@ use crate::vote::Vote;
 #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize, Encode, Decode, TreeHash)]
 pub struct SignedBlock {
     pub message: Block,
-    pub signature: PQSignature,
+    pub signature: FixedBytes<4000>,
```
Comment (unnawut) [inline crates/common/consensus/lean/src/block.rs:17]: Hmm totally need advice here. Once I change to this, I get this lint error:

```
error: large size difference between variants
  --> crates/networking/p2p/src/req_resp/lean/messages/mod.rs:36:1
   |
36 | / pub enum LeanResponseMessage {
37 | |     Status(LeanStatus),
   | |     ------------------ the second-largest variant contains at least 80 bytes
38 | |     BlocksByRoot(SignedBlock),
   | |     ------------------------- the largest variant contains at least 4104 bytes
39 | | }
   | |_^ the entire enum is at least 4104 bytes
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
   = note: `-D clippy::large-enum-variant` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::large_enum_variant)]`
help: consider boxing the large fields to reduce the total size of the enum
   |
38 -     BlocksByRoot(SignedBlock),
38 +     BlocksByRoot(Box<SignedBlock>),
   |

error: large size difference between variants
  --> crates/networking/p2p/src/req_resp/messages.rs:29:1
   |
29 | / pub enum ResponseMessage {
30 | |     Beacon(Arc<BeaconResponseMessage>),
   | |     ---------------------------------- the second-largest variant contains at least 8 bytes
31 | |     Lean(LeanResponseMessage),
   | |     ------------------------- the largest variant contains at least 4104 bytes
32 | | }
   | |_^ the entire enum is at least 4104 bytes
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
help: consider boxing the large fields to reduce the total size of the enum
   |
31 -     Lean(LeanResponseMessage),
31 +     Lean(Box<LeanResponseMessage>),
   |
```

Comment (KolbyML) [reply crates/common/consensus/lean/src/block.rs:17]: Depending on the context I would use a Box or a Arc. Try a box, but if it needs SSZ encoding then you will have to use an arc

**Comment by unnawut** [comment]
Ready for review!

Also please take note that there's [state.rs file](https://github.com/ReamLabs/ream/pull/755/files#diff-a7d630b406cdd46523f5b854dc367f8677aed953706b4a41e9813554b6bc3c89) that got auto-collapsed by Github and it has the biggest chunks of changes.

File: crates/common/consensus/lean/src/attestation.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+use crate::vote::Vote;
+
+/// Represents an attestation in the Lean chain.
+///
+/// See the [Lean specification](https://github.com/leanEthereum/leanSpec/blob/main/docs/client/containers.md#attestation)
+/// for detailed protocol information.
+#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize, Encode, Decode, TreeHash)]
+pub struct Attestation {
+    // U4096 = VALIDATOR_REGISTRY_LIMIT
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/attestation.rs]:
```suggestion
    /// U4096 = VALIDATOR_REGISTRY_LIMIT
```

this should be a doc comment

File: crates/common/consensus/lean/src/attestation.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+    pub aggregation_bits: BitList<U4096>,
+    pub message: Vote,
+    pub signature: VariableList<B8, 4000>,
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/attestation.rs]: why b8 here and not u8?

File: crates/common/consensus/lean/src/state.rs [hunk 4]
```diff
@@ -48,126 +59,343 @@ impl LeanState {
...
-            )
-            .map_err(|err| anyhow!("Failed to set justification bit: {err:?}"))?;
+        let block = &signed_block.message;
+
+        // Process slots (including those with no blocks) since block
+        self.process_slots(block.slot)
+            .expect("Failed to process slots");
+
+        // Process block
+        self.process_block(block).expect("Failed to process block");
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/state.rs]: we shouldn't be using expect here

File: crates/common/consensus/lean/src/state.rs [hunk 5]
```diff
@@ -48,126 +59,343 @@ impl LeanState {
...
+        attestations: &VariableList<Arc<SignedVote>, U4096>,
+    ) -> anyhow::Result<()> {
+        let mut justifications_map = self.get_justifications()?;
+
+        for signed_vote in attestations {
+            let vote = &signed_vote.data;
+            // Ignore votes whose source is not already justified,
+            // or whose target is not in the history, or whose target is not a
+            // valid justifiable slot
+            if !self.justified_slots[vote.source.slot as usize] {
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/state.rs]: shouldn't we use get() instead of raw parses for bounds checks? and to avoid panics

**Review by KolbyML — COMMENTED** [review]
Most of the PR looks fine, my main concern is didn't we go a little overboard with Arc<>'s a lot of places we are using arc's now it doesn't look like it is needed

**Comment by KolbyML** [comment]
image

^ this is probably the only part in this PR which should be using Arc's

File: crates/common/consensus/lean/src/attestation.rs (hunk 2 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/attestation.rs]: Updated in [c964b3b](https://github.com/ReamLabs/ream/pull/755/commits/c964b3b257e7e39fa65dc937800dc705d81e3f84)

File: crates/common/consensus/lean/src/attestation.rs (hunk 3 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/attestation.rs]: Updated in a552800

File: crates/common/consensus/lean/src/state.rs (hunk 4 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: Updated in 046ef0a

File: crates/common/consensus/lean/src/state.rs (hunk 5 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: Updated in d7740d9

File: crates/common/consensus/lean/src/vote.rs [hunk 6]
```diff
@@ -12,7 +12,7 @@ use crate::checkpoint::Checkpoint;
 #[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize, Encode, Decode, TreeHash)]
 pub struct SignedVote {
     pub data: Vote,
-    pub signature: PQSignature,
+    pub signature: FixedBytes<4000>,
 }
```
Comment (syjn99) [inline crates/common/consensus/lean/src/vote.rs]:
```suggestion
#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize, Encode, Decode, TreeHash)]
pub struct SignedVote {
    pub validator_id: uint64
    pub message: Vote,
    pub signature: FixedBytes<4000>,
}

```

Refer to `SignedVote` [definition](https://github.com/leanEthereum/leanSpec/blob/main/docs/client/containers.md#signedvote).

Comment (syjn99) [reply crates/common/consensus/lean/src/vote.rs]: Also note that we should delete `validator_id` in `Vote`.

File: crates/common/chain/lean/src/p2p_request.rs [hunk 7]
```diff
@@ -1,7 +1,9 @@
+use std::sync::Arc;
+
 use ream_consensus_lean::{block::SignedBlock, vote::SignedVote};
 
 #[derive(Debug, Clone)]
 pub enum LeanP2PRequest {
-    GossipBlock(SignedBlock),
-    GossipVote(SignedVote),
+    GossipBlock(Arc<SignedBlock>),
+    GossipVote(Arc<SignedVote>),
```
Comment (syjn99) [inline crates/common/chain/lean/src/p2p_request.rs]: Hmm same with Kolby's comment, we have lots of unnecessary `Arc` usage everywhere.

File: crates/common/consensus/lean/src/block.rs [hunk 8]
```diff
@@ -70,5 +71,5 @@ impl From<Block> for BlockHeader {
     Debug, Default, PartialEq, Eq, Clone, Serialize, Deserialize, Encode, Decode, TreeHash,
 )]
 pub struct BlockBody {
-    pub votes: VariableList<Vote, U4096>,
+    pub attestations: VariableList<Arc<SignedVote>, U4096>,
```
Comment (syjn99) [inline crates/common/consensus/lean/src/block.rs]:
```suggestion
    pub attestations: VariableList<SignedVote, U4096>,
```

I think this part doesn't need `Arc` as well.

File: crates/common/consensus/lean/src/state.rs [hunk 9]
```diff
@@ -48,126 +59,362 @@ impl LeanState {
...
         }
     }
 
-    fn get_justifications_roots_index(&self, root: &B256) -> Option<usize> {
-        self.justifications_roots.iter().position(|r| r == root)
-    }
+    /// Returns a map of `root -> justifications` constructed from the
+    /// flattened data in the state.
+    pub fn get_justifications(&self) -> anyhow::Result<HashMap<B256, BitList<U4096>>> {
+        let mut justifications_map = HashMap::<B256, BitList<U4096>>::new();
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs]:
```suggestion
        let mut justifications_map = HashMap::new();
```

We don't need explicit type here.

File: crates/common/consensus/lean/src/state.rs [hunk 10]
```diff
@@ -48,126 +59,362 @@ impl LeanState {
...
+            .expect("Failed to initialize an empty BitList"),
         }
     }
 
-    fn get_justifications_roots_index(&self, root: &B256) -> Option<usize> {
-        self.justifications_roots.iter().position(|r| r == root)
-    }
+    /// Returns a map of `root -> justifications` constructed from the
+    /// flattened data in the state.
+    pub fn get_justifications(&self) -> anyhow::Result<HashMap<B256, BitList<U4096>>> {
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs:72]: In this function, can we align the variable names with the specification code?

For example,

- `justifications_map` -> `justifications`
- `justifications` -> `votes_list`

Comment (syjn99) [reply crates/common/consensus/lean/src/state.rs:72]: Same comment for `set_justifications`.

File: crates/common/consensus/lean/src/state.rs [hunk 11]
```diff
@@ -48,126 +59,362 @@ impl LeanState {
...
-                .set(i, bit)
-                .map_err(|err| {
-                    anyhow!("Failed to initialize justification bits to existing values: {err:?}")
+        let mut sorted_roots = justifications_map.keys().collect::<Vec<_>>();
+        sorted_roots.sort();
+
+        for (root_index, root) in sorted_roots.iter().enumerate() {
+            let justifications = justifications_map
+                .get(*root)
+                .ok_or_else(|| anyhow!("Root {root:?} not found in justifications_map"))?;
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs]:
```suggestion
                .ok_or_else(|| anyhow!("Root {root} not found in justifications_map"))?;
```

File: crates/common/consensus/lean/src/state.rs [hunk 12]
```diff
@@ -48,126 +59,362 @@ impl LeanState {
...
 
-        for (i, bit) in self.justifications_roots_validators.iter().enumerate() {
-            new_justifications_roots_validators
-                .set(i, bit)
-                .map_err(|err| {
-                    anyhow!("Failed to initialize justification bits to existing values: {err:?}")
+        let mut sorted_roots = justifications_map.keys().collect::<Vec<_>>();
+        sorted_roots.sort();
+
+        for (root_index, root) in sorted_roots.iter().enumerate() {
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs]:
```suggestion
        for (root_index, root) in justifications_map.keys().sorted().enumerate() {
```

We can use `itertools` here for cleaner and readable code. You might have to import like:

```rust
use itertools::Itertools;
```

File: crates/common/consensus/lean/src/state.rs [hunk 13]
```diff
@@ -48,126 +59,362 @@ impl LeanState {
...
-            new_justifications_roots_validators
-                .set(i, justification_bit)
-                .map_err(|err| anyhow!("Failed to set new justification bit: {err:?}"))?;
+        // genesis block is always justified
+        let is_justified = self.latest_block_header.slot == 0;
+
+        self.justified_slots
+            .push(is_justified)
+            .map_err(|err| anyhow!("Failed to add to justified_slots: {err:?}"))?;
+
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs]:
```suggestion
        // genesis block is always justified
        self.justified_slots
            .push(self.latest_block_header.slot == 0;)
            .map_err(|err| anyhow!("Failed to add to justified_slots: {err:?}"))?;

```

Hmm I'm afraid `is_justified` is not that descriptive here, so would suggest to inline it,

**Review by syjn99 — COMMENTED** [review]
Left some comments here. I also think removing `Arc` as possible as we can should be done. But nice work!

File: crates/common/consensus/lean/src/vote.rs (hunk 6 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/vote.rs]: Fixed in e0840ac

File: crates/common/consensus/lean/src/state.rs (hunk 9 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: Fixed in dc5b43b

File: crates/common/consensus/lean/src/state.rs (hunk 11 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: Fixed in cbc1f3a

File: crates/common/consensus/lean/src/state.rs (hunk 13 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: Fixed in fc4a09f

File: crates/common/consensus/lean/src/block.rs (hunk 8 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/block.rs]: Fixed in 1c1f174

File: crates/common/chain/lean/src/p2p_request.rs (hunk 7 above)
Comment (unnawut) [reply crates/common/chain/lean/src/p2p_request.rs]: Fixed in 1c1f174

File: crates/common/consensus/lean/src/state.rs (hunk 10 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs:72]: Fixed in 87a41f7. Will follow with `set_justifications` changes

Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs:72]: Fixed in 0ca97cb

File: crates/common/consensus/lean/src/state.rs (hunk 12 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs]: This is new to me. Thanks! Fixed in 0ca97cb

File: crates/common/consensus/lean/src/state.rs (hunk 10 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs:72]: `set_justifications` in 0ca97cb

File: crates/common/chain/lean/src/genesis.rs [hunk 14]
```diff
@@ -1,16 +1,15 @@
 use alloy_primitives::B256;
 use ream_consensus_lean::{
-    block::{Block, BlockBody},
+    block::{Block, BlockBody, BlockHeader},
     state::LeanState,
 };
 use ream_network_spec::networks::lean_network_spec;
 use tree_hash::TreeHash;
 
 fn genesis_block(state_root: B256) -> Block {
```
Comment (syjn99) [inline crates/common/chain/lean/src/genesis.rs:9]:
```rust
fn genesis_block(state_root: B256) -> Block {
    Block {
        state_root,
        ..Default::default()
    }
}
```

We might use `Default` trait in this context as it doesn't have much meaning right now. Feel free to change, just a suggestion!

File: crates/common/chain/lean/src/queue_item.rs [hunk 15]
```diff
@@ -1,8 +1,8 @@
...
+use ream_consensus_lean::{block::SignedBlock, vote::SignedVote};
 use serde::{Deserialize, Serialize};
 
 #[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
 pub enum QueueItem {
-    Block(Block),
-    Vote(Vote),
+    SignedBlock(SignedBlock),
+    SignedVote(SignedVote),
 }
```
Comment (syjn99) [inline crates/common/chain/lean/src/queue_item.rs:8]: Hmm I think these changes are super fine in this phase, but after we have a signature verification logic, it must be a bottleneck to re-verify those `Signed*` objects. But we can think of this issue later on after devnet0.

File: crates/common/consensus/lean/src/state.rs [hunk 16]
```diff
@@ -48,126 +60,373 @@ impl LeanState {
...
+    pub fn process_attestations(
+        &mut self,
+        attestations: &VariableList<SignedVote, U4096>,
+    ) -> anyhow::Result<()> {
+        // get justifications, justified slots and historical block hashes are
+        // already up to date as per the processing in process_block_header
+        let mut justifications_map = self.get_justifications()?;
+
+        for signed_vote in attestations {
```
Comment (syjn99) [inline crates/common/consensus/lean/src/state.rs:298]: I like those step-by-step validations and the clear error message :)

File: crates/common/chain/lean/src/service.rs [hunk 17]
```diff
@@ -169,17 +183,23 @@ impl LeanChainService {
...
 
-        match lean_chain.post_states.get(&block.parent_root) {
+        match lean_chain
+            .post_states
+            .get(&signed_block.message.parent_root)
+        {
             Some(parent_state) => {
-                let state = process_block(parent_state, &block)?;
+                let mut state = parent_state.clone();
+                state.state_transition(&signed_block, true, false)?;
```
Comment (syjn99) [inline crates/common/chain/lean/src/service.rs]: hmm does `validate_result` should be true in this case?

File: crates/common/chain/lean/src/queue_item.rs (hunk 15 above)
Comment (unnawut) [reply crates/common/chain/lean/src/queue_item.rs:8]: Maybe I'm missing something but the reason I changed to `Signed*` is because [`BlockBody::attestations` now requires `SignedVote` instead of `Vote`](https://github.com/ReamLabs/ream/pull/755/files#diff-c9d12999c834374d1eb1bc16616919abd46a00e75f80fc41b5173826513a060eL73), so I need to retain the signature until each vote is included into the block.

But also looks like I only need `SignedVote` so I've reverted back `SignedBlock` to `Block` in 79ed881

File: crates/common/chain/lean/src/genesis.rs (hunk 14 above)
Comment (unnawut) [reply crates/common/chain/lean/src/genesis.rs:9]: Fixed in f680e44

File: crates/common/consensus/lean/src/state.rs (hunk 16 above)
Comment (unnawut) [reply crates/common/consensus/lean/src/state.rs:298]: Debugging this was a real pain 😭

File: crates/common/chain/lean/src/service.rs (hunk 17 above)
Comment (unnawut) [reply crates/common/chain/lean/src/service.rs]: Fixed in aa82086

File: crates/common/chain/lean/src/queue_item.rs (hunk 15 above)
Comment (unnawut) [reply crates/common/chain/lean/src/queue_item.rs:8]: And now `QueueItem::SignedVote(Box<SignedVote>)` because of line error: `large size difference between variants`: 641fcce

**Review by syjn99 — APPROVED** [review]
LGTM! Nice work

File: crates/common/consensus/lean/src/lib.rs [hunk 18]
```diff
@@ -117,7 +44,7 @@ pub fn get_latest_justified_hash(post_states: &HashMap<B256, LeanState>) -> Opti
 pub fn get_fork_choice_head(
     blocks: &HashMap<B256, Block>,
     provided_root: &B256,
-    votes: &[Vote],
+    votes: &Vec<SignedVote>,
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/lib.rs]:
```suggestion
    votes: &[SignedVote],
```

we shouldn't be passing references to a vector, we should just pass a slice assuming there are no stack problems due to the underlying datatypes

File: crates/common/consensus/lean/src/state.rs [hunk 19]
```diff
@@ -48,126 +60,373 @@ impl LeanState {
...
+        validate_result: bool,
+    ) -> anyhow::Result<()> {
+        // Verify signatures
+        ensure!(valid_signatures, "Signatures are not valid");
+
+        let block = &signed_block.message;
+
+        // Process slots (including those with no blocks) since block
+        self.process_slots(block.slot)
+            .context("Failed to process slots")?;
```
Comment (KolbyML) [inline crates/common/consensus/lean/src/state.rs:165]: nice anyhow find (not sure if it was Jun or you) but this is def clean if we are using an anyhow result

**Review by KolbyML — APPROVED** [review]
:shipit: PR overall looks good. Nice find with `context`. Generally we should pass slices instead of references to vectors, there are very few exception, but if this is an exception where it makes sense just let me know
