### PR TITLE
feat: fix Beacon API content type

### LINKED ISSUE #405: Fix Beacon API content type
### Describe the feature

Some beacon APIs in Ream have Json encoding for paramaters which means they need to be passed in the Body section. In reality, no getter beacon APIs have Body input requirement(I still need recheck this). They should all be passed in the query itself

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by varun-doshi**
### What are you trying to achieve?

Fixes #405

### Details:

Some `GET` endpoints were using `Json` as their input which meant they need be passed in the `body` section of the request. As per spec, these endpoints should only have `Path` and `Query` types in the request i.e. the endpoints should look something like this:
```
http://localhost/eth/v1/beacon/blob_sidecars/head?indices=1&indices=4
```
But these were failing in Ream since they were in `Json` format. 
Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .

Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).

Note: This issue pertains only to `GET` endpoints. `POST` endpoints generally require `body` so thats okay

### Testing: 

I've tested the updated implementations and they are all working as expected now.

### CODE REVIEW

**Comment by KolbyML** [comment]
> Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .
> 
> Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).

Why would we want to support duplicate keys?

**Comment by varun-doshi** [comment]
> > Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .
> > Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).
> 
> Why would we want to support duplicate keys?

this is what i meant:
```
http://localhost/eth/v1/beacon/blob_sidecars/head?indices=1&indices=4
```


Its how it is in the official specs

**Comment by KolbyML** [comment]
> > > Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .
> > > Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).
> > 
> > 
> > Why would we want to support duplicate keys?
> 
> this is what i meant:
> 
> ```
> http://localhost/eth/v1/beacon/blob_sidecars/head?indices=1&indices=4
> ```
> 
> Its how it is in the official specs

Can we remove the custom macro and just use
https://github.com/actix/actix-web/issues/1301#issuecomment-1873831135

image

**Comment by varun-doshi** [comment]
> > > > Solely switching from `Json` to `Query` type in `actix-web` does not do the trick because `actix` does not support duplicate name keys in the query as per this [discussion](https://github.com/actix/actix-web/issues/1301) .
> > > > Hence the only way to format it as per spec is to implement a custom deserializer ourselves(which I've done and changed it to a macro for ease of use).
> > > 
> > > 
> > > Why would we want to support duplicate keys?
> > 
> > 
> > this is what i meant:
> > ```
> > http://localhost/eth/v1/beacon/blob_sidecars/head?indices=1&indices=4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Its how it is in the official specs
> 
> Can we remove the custom macro and just use [actix/actix-web#1301 (comment)](https://github.com/actix/actix-web/issues/1301#issuecomment-1873831135)
> 
> image

looking into this

**Comment by varun-doshi** [comment]
@KolbyML ready for another look

File: crates/rpc/src/handlers/blob_sidecar.rs [hunk 1]
```diff
@@ -27,7 +28,7 @@ pub async fn get_blob_sidecars(
             if index >= &max_index {
                 return Err(ApiError::BadRequest(format!(
                     "Invalid blob index: {index}, max index is {}",
-                    max_index - 1
+                    max_index
```
Comment (KolbyML) [inline crates/rpc/src/handlers/blob_sidecar.rs:31]: can you inline max_index
